# Generated by Django 3.1.6 on 2021-02-19 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(3, 'Please create a title greater than 3 characters')])),
                ('post', models.TextField()),
                ('topic_category', models.CharField(choices=[('ADVICE & RESOURCES-GENERAL', 'ADVICE & RESOURCES-GENERAL'), ('ADVICE & RESOURCES-CAREER', 'ADVICE & RESOURCES-CAREER'), ('BIPOC IN TECH', 'BIPOC IN TECH'), ('CAREER CHANGER', 'CAREER CHANGER'), ('CAREER DEVELOPMENT', 'CAREER DEVELOPMENT'), ('ENTREPRENEURSHIP', 'ENTREPRENEURSHIP'), ('IN THE WORKPLACE', 'IN THE WORKPLACE'), ('Q & A', 'Q & A'), ('MOMMY IN TECH', 'MOMMY IN TECH'), ('NETWORKING', 'NETWORKING'), ('NEW TO TECH', 'NEW TO TECH'), ('TECH TALK', 'TECH TALK')], default='NEW TO TECH', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
